#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/ops/lib/common.sh"
ensure_repo_root

ENV_DIR="${OP_BRIDGE_ENV_DIR:-$(default_env_dir)}"
mkdir -p "$ENV_DIR"

write_if_missing() {
  local file="$1"
  local content="$2"
  if [[ -f "$file" ]]; then
    echo "Skip existing: $file"
    return
  fi
  printf '%s\n' "$content" >"$file"
  echo "Created: $file"
}

write_if_missing "$ENV_DIR/relayer-common.env" '# Shared relayer config
SEPOLIA_RPC_URL=
OPNET_NETWORK=testnet
OPNET_RPC_URL=https://testnet.opnet.org
RELAYER_MAPPING_FILE=
ATTESTATION_VERSION=1
RELAYER_POLL_INTERVAL_MS=30000
RELAYER_API_URL=http://127.0.0.1:8787
RELAYER_API_DB_PATH=
# RELAYER_API_WRITE_TOKEN=
# RELAYER_DISABLE_FILE_OUTPUT=1
'

write_if_missing "$ENV_DIR/relayer-api.env" '# Relayer API service
RELAYER_API_HOST=127.0.0.1
RELAYER_API_PORT=8787
RELAYER_API_DB_PATH=
# RELAYER_API_CORS_ALLOWED_ORIGINS=https://testnet.opbridge.app,https://testnet.opbridge.app,https://*.vercel.app,http://localhost:5173,http://127.0.0.1:5173
# RELAYER_API_WRITE_TOKEN=
'

write_if_missing "$ENV_DIR/aggregator.env" '# Aggregator DB/API-first mode
RELAYER_ATTESTATION_SOURCE=db
RELAYER_API_DB_PATH=
RELAYER_API_URL=http://127.0.0.1:8787
RELAYER_DISABLE_FILE_OUTPUT=1
RELAYER_THRESHOLD=2
# RELAYER_API_WRITE_TOKEN=
'

for name in sepolia-a sepolia-b sepolia-c; do
  idx=0
  [[ "$name" == "sepolia-b" ]] && idx=1
  [[ "$name" == "sepolia-c" ]] && idx=2
  write_if_missing "$ENV_DIR/${name}.env" "RELAYER_ID=relayer-${name##*-}
RELAYER_INDEX=${idx}
RELAYER_SIGNER_MODE=kms
RELAYER_KMS_KEY_ID=
RELAYER_MAX_BLOCK_RANGE=10
RELAYER_OUTPUT_FILE=/home/ssm-user/opbridge/services/relayer/.data/attestations/relayer-${name##*-}.json
# RELAYER_START_BLOCK=
"
done

for name in opnet-burn-a opnet-burn-b opnet-burn-c; do
  idx=0
  [[ "$name" == "opnet-burn-b" ]] && idx=1
  [[ "$name" == "opnet-burn-c" ]] && idx=2
  suffix="${name##*-}"
  write_if_missing "$ENV_DIR/${name}.env" "RELAYER_ID=relayer-opnet-${suffix}
RELAYER_INDEX=${idx}
RELAYER_EVM_SIGNER_MODE=kms
RELAYER_EVM_KMS_KEY_ID=
RELAYER_MAX_BLOCK_RANGE=5
RELAYER_OUTPUT_FILE=/home/ssm-user/opbridge/services/relayer/.data/release-attestations/relayer-opnet-${suffix}.json
# RELAYER_START_BLOCK=
"
done

write_if_missing "$ENV_DIR/contracts.env" '# Generated by scripts/opbridge-env-sync.sh
# Ethereum + OPNet addresses used by relayers and site
'

echo
echo "opbridge-env initialized at: $ENV_DIR"
echo "Next: run scripts/opbridge-env-sync.sh after deployments to populate contract addresses."
