#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/ops/lib/common.sh"
ensure_repo_root
require_cmd node

ENV_DIR="${OP_BRIDGE_ENV_DIR:-$(default_env_dir)}"
DEPLOYMENT_FILE="${ETHEREUM_DEPLOYMENT_FILE:-${SEPOLIA_DEPLOYMENT_FILE:-$(pwd)/contracts/ethereum/deployments/sepolia-latest.json}}"

mkdir -p "$ENV_DIR"

require_env OPNET_BRIDGE_ADDRESS
require_env OPNET_BRIDGE_HEX
require_env OPNET_HUSDT_ADDRESS
require_env OPNET_HWBTC_ADDRESS
require_env OPNET_HETH_ADDRESS
require_env OPNET_HPAXG_ADDRESS

if [[ ! -f "$DEPLOYMENT_FILE" ]]; then
  echo "Deployment file not found: $DEPLOYMENT_FILE" >&2
  exit 1
fi

mapfile -t DEPLOY_VARS < <(node - "$DEPLOYMENT_FILE" <<'NODE'
const fs = require('fs');
const path = process.argv[2];
const d = JSON.parse(fs.readFileSync(path,'utf8'));
const out = [];
out.push(`ETHEREUM_VAULT_ADDRESS=${d.vaultAddress||''}`);
for (const asset of (d.assets||[])) {
  const key = `ETHEREUM_${String(asset.symbol||'').toUpperCase()}_ADDRESS`;
  out.push(`${key}=${asset.tokenAddress||''}`);
}
console.log(out.join('\n'));
NODE
)

CONTRACTS_ENV="$ENV_DIR/contracts.env"
: > "$CONTRACTS_ENV"
{
  echo "# Generated by scripts/opbridge-env-sync.sh on $(date -u +%FT%TZ)"
  echo "ETHEREUM_DEPLOYMENT_FILE=$DEPLOYMENT_FILE"
  printf '%s\n' "${DEPLOY_VARS[@]}"
  echo "OPNET_BRIDGE_ADDRESS=${OPNET_BRIDGE_ADDRESS}"
  echo "OPNET_BRIDGE_HEX=${OPNET_BRIDGE_HEX}"
  echo "OPNET_HUSDT_ADDRESS=${OPNET_HUSDT_ADDRESS}"
  echo "OPNET_HWBTC_ADDRESS=${OPNET_HWBTC_ADDRESS}"
  echo "OPNET_HETH_ADDRESS=${OPNET_HETH_ADDRESS}"
  echo "OPNET_HPAXG_ADDRESS=${OPNET_HPAXG_ADDRESS}"
} >> "$CONTRACTS_ENV"

RELAYER_COMMON="$ENV_DIR/relayer-common.env"
touch "$RELAYER_COMMON"
upsert_env_line "$RELAYER_COMMON" "RELAYER_MAPPING_FILE" "$DEPLOYMENT_FILE"
upsert_env_line "$RELAYER_COMMON" "OPNET_BRIDGE_ADDRESS" "$OPNET_BRIDGE_ADDRESS"
upsert_env_line "$RELAYER_COMMON" "OPNET_BRIDGE_HEX" "$OPNET_BRIDGE_HEX"

API_DB_DEFAULT="${HOME}/opbridge/services/api/.data/relayer-api.sqlite"
if ! grep -qE '^RELAYER_API_DB_PATH=' "$RELAYER_COMMON"; then
  echo "RELAYER_API_DB_PATH=$API_DB_DEFAULT" >> "$RELAYER_COMMON"
fi

for f in "$ENV_DIR/relayer-api.env" "$ENV_DIR/aggregator.env"; do
  touch "$f"
  upsert_env_line "$f" "RELAYER_API_DB_PATH" "$API_DB_DEFAULT"
done

SITE_ENV_LOCAL="$(pwd)/apps/site/.env.local"
: > "$SITE_ENV_LOCAL"
{
  echo "# Generated by scripts/opbridge-env-sync.sh on $(date -u +%FT%TZ)"
  echo "VITE_STATUS_API_URL=${VITE_STATUS_API_URL:-}"
  echo "VITE_ETHEREUM_VAULT_ADDRESS=$(printf '%s\n' "${DEPLOY_VARS[@]}" | awk -F= '/^ETHEREUM_VAULT_ADDRESS=/{print $2}')"
  echo "VITE_ETHEREUM_USDT_ADDRESS=$(printf '%s\n' "${DEPLOY_VARS[@]}" | awk -F= '/^ETHEREUM_USDT_ADDRESS=/{print $2}')"
  echo "VITE_ETHEREUM_WBTC_ADDRESS=$(printf '%s\n' "${DEPLOY_VARS[@]}" | awk -F= '/^ETHEREUM_WBTC_ADDRESS=/{print $2}')"
  echo "VITE_ETHEREUM_WETH_ADDRESS=$(printf '%s\n' "${DEPLOY_VARS[@]}" | awk -F= '/^ETHEREUM_WETH_ADDRESS=/{print $2}')"
  echo "VITE_ETHEREUM_PAXG_ADDRESS=$(printf '%s\n' "${DEPLOY_VARS[@]}" | awk -F= '/^ETHEREUM_PAXG_ADDRESS=/{print $2}')"
  echo "VITE_OPNET_BRIDGE_ADDRESS=${OPNET_BRIDGE_ADDRESS}"
  echo "VITE_OPNET_FEE_RATE=${VITE_OPNET_FEE_RATE:-2}"
  echo "VITE_OPNET_MAX_SAT_SPEND=${VITE_OPNET_MAX_SAT_SPEND:-20000}"
} >> "$SITE_ENV_LOCAL"

echo "Wrote $CONTRACTS_ENV"
echo "Updated $RELAYER_COMMON"
echo "Updated $ENV_DIR/relayer-api.env and $ENV_DIR/aggregator.env (DB path defaults)"
echo "Wrote apps/site/.env.local"
